@yahoo.com
alexibot
alligator
anonymiz
asterias
backdoorbot
black hole
blackwidow
blowfish
botalot
builtbottough
bullseye
bunnyslippers
catch
cegbfeieh
charon
cheesebot
cherrypicker
chinaclaw
combine
copyrightcheck
cosmos
crescent
curl
dbrowse
disco
dittospyder
dlman
dnloadmage
download
dreampassport
dts agent
ecatch
eirgrabber
erocrawler
express webpictures
extractorpro
eyenetie
fantombrowser
fantomcrew browser
fileheap
filehound
flashget
foobot
franklin locator
freshdownload
fscrawler
gamespy_arcade
getbot
getright
getweb
go!zilla
go-ahead-got-it
grab
grafula
gsa-crawler
harvest
hloader
hmview
httplib
httpresume
httrack
humanlinks
igetter
image stripper
image sucker
industry program
indy library
infonavirobot
installshield digitalwizard
interget
iria
irvine
iupui research bot
jbh agent
jennybot
jetcar
jobo
joc
kapere
kenjin spider
keyword density
larbin
leechftp
leechget
lexibot
libweb/clshttp
libwww-perl
lightningdownload
lincoln state web browser
linkextractorpro
linkscan/8.1a.unix
linkwalker
lwp-trivial
lwp::simple
mac finder
mata hari
mediasearch
metaproducts
microsoft url control
midown tool
miixpc
missauga locate
missouri college browse
mister pix
moget
mozilla.*newt
mozilla/3.0 (compatible)
mozilla/3.mozilla/2.01
msie 4.0 (win95)
multiblocker browser
mydaemon
mygetright
nabot
navroad
nearsite
net vampire
netants
netmechanic
netpumper
netspider
newsearchengine
nicerspro
ninja
nitro downloader
npbot
octopus
offline explorer
offline navigator
openfind
pagegrabber
papa foto
pavuk
pbrowse
pcbrowser
peval
pompos/
program shareware
propowerbot
prowebwalker
psurf
puf
puxarapido
queryn metasearch
realdownload
reget
repomonkey
rsurf
rumours-agent
sakura
scan4mail
semanticdiscovery
sitesnagger
slysearch
spankbot
spanner 
spiderzilla
sq webscanner
stamina
star downloader
steeler
steeler
strip
superbot
superhttp
surfbot
suzuran
swbot
szukacz
takeout
teleport
telesoft
test spider
the intraformant
thenomad
tighttwatbot
titan
tocrawl/urldispatcher
true_robot
tsurf
turing machine
turingos
urlblaze
urlgetfile
urly warning
utilmind
vci
voideye
web image collector
web sucker
webauto
webbandit
webcapture
webcollage
webcopier
webenhancer
webfetch
webgo
webleacher
webmasterworldforumbot
webql
webreaper
website extractor
website quester
webster
webstripper
webwhacker
wep search
wget
whizbang
widow
wildsoft surfer
www-collector-e
www.netwu.com
wwwoffle
xaldon
xenu
zeus
ziggy
zippy